name: depampbot
description: A dependency management bot for Dart.
version: 0.0.0-1
homepage: https://github.com/Ampless/depampbot
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  pub_api: ^0.1.0
  github: ^9.0.0
  pubspec_parse: ^1.0.0
  pub_semver: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
