name: depampbot
description: A dependency management bot for Dart.
homepage: https://github.com/Ampless/depampbot

publish_to: 'none'

version: 0.0.0-1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pub_api: ^0.0.3

dev_dependencies:
  pedantic: ^1.9.2
